# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md
name: Check Markdown

env:
  # See: https://github.com/actions/setup-node/#readme
  NODE_VERSION: 16.x

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-markdown-task.ya?ml"
      - ".markdown-link-check.json"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "**/.markdownlint*"
      - "**.mdx?"
      - "**.mkdn"
      - "**.mdown"
      - "**.markdown"
  pull_request:
    paths:
      - ".github/workflows/check-markdown-task.ya?ml"
      - ".markdown-link-check.json"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "**/.markdownlint*"
      - "**.mdx?"
      - "**.mkdn"
      - "**.mdown"
      - "**.markdown"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by external changes.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Initialize markdownlint-cli problem matcher
        uses: xt0rted/markdownlint-problem-matcher@v3

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Lint
        run: task markdown:lint

  links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Check links
        run: task --silent markdown:check-links
